/**
 * Comprehensive Food Database for Eco Eating Guide
 * Contains 120+ food items with real nutritional data
 * Based on USDA FoodData Central and environmental impact studies
 */

export type FoodCategory = 
  | "Fruits"
  | "Vegetables"
  | "Grains & Cereals"
  | "Legumes & Pulses"
  | "Dairy & Alternatives"
  | "Meat & Protein"
  | "Nuts & Seeds"
  | "Oils & Fats"
  | "Beverages"
  | "Snacks & Others";

export type ImpactLevel = "Low" | "Medium" | "High";
export type HealthRating = "Excellent" | "Good" | "Moderate" | "Limited";

export interface NutritionInfo {
  calories: number;
  protein: number; // grams
  fat: number; // grams
  carbs: number; // grams
  fiber: number; // grams
  vitamins: string[];
}

export interface FoodItem {
  id: string;
  name: string;
  category: FoodCategory;
  emoji?: string;
  co2PerServing: number; // kg CO2e per serving
  servingSize: string; // e.g., "1 medium apple"
  servingGrams: number; // grams
  nutrition: NutritionInfo;
  seasonality: number[]; // 0-11 for Jan-Dec
  sustainabilityNote: string;
  ecoScore: ImpactLevel;
  healthScore: HealthRating;
  advice: string;
  waterFootprint?: number; // liters per serving
}

// Helper function to determine eco impact
const getEcoScore = (co2: number): ImpactLevel => {
  if (co2 < 0.5) return "Low";
  if (co2 < 1.5) return "Medium";
  return "High";
};

const getHealthScore = (nutrition: NutritionInfo): HealthRating => {
  const score = 
    (nutrition.fiber / 10) * 25 + 
    (nutrition.protein / 20) * 25 + 
    ((nutrition.vitamins.length / 5) * 25) +
    (nutrition.carbs / 50) * 25;
  
  if (score >= 80) return "Excellent";
  if (score >= 60) return "Good";
  if (score >= 40) return "Moderate";
  return "Limited";
};

// ===== FRUITS (18 items) =====
const fruitDatabase: FoodItem[] = [
  {
    id: "apple",
    name: "Apple",
    category: "Fruits",
    emoji: "🍎",
    co2PerServing: 0.04,
    servingSize: "1 medium (182g)",
    servingGrams: 182,
    nutrition: { calories: 95, protein: 0.5, fat: 0.3, carbs: 25, fiber: 4.4, vitamins: ["Vit C", "Potassium", "Antioxidants"] },
    seasonality: [7, 8, 9, 10, 11],
    sustainabilityNote: "Very low carbon footprint if locally sourced.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Perfect snack. Local varieties preferred.",
    waterFootprint: 125
  },
  {
    id: "banana",
    name: "Banana",
    category: "Fruits",
    emoji: "🍌",
    co2PerServing: 0.11,
    servingSize: "1 medium (118g)",
    servingGrams: 118,
    nutrition: { calories: 105, protein: 1.3, fat: 0.4, carbs: 27, fiber: 3.1, vitamins: ["Vit B6", "Potassium", "Vit C"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Shipped sustainably by boat. Choose Fair Trade when possible.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Great energy source. Fair Trade preferred.",
    waterFootprint: 160
  },
  {
    id: "orange",
    name: "Orange",
    category: "Fruits",
    emoji: "🍊",
    co2PerServing: 0.09,
    servingSize: "1 medium (131g)",
    servingGrams: 131,
    nutrition: { calories: 62, protein: 1.2, fat: 0.2, carbs: 15, fiber: 3.1, vitamins: ["Vit C", "Folate", "Thiamine"] },
    seasonality: [11, 0, 1, 2, 3],
    sustainabilityNote: "Low water footprint. Eat fresh, avoid juice.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Immunity booster. Eat whole fruit.",
    waterFootprint: 860
  },
  {
    id: "berries",
    name: "Mixed Berries",
    category: "Fruits",
    emoji: "🫐",
    co2PerServing: 0.15,
    servingSize: "1 cup (150g)",
    servingGrams: 150,
    nutrition: { calories: 85, protein: 1.2, fat: 0.6, carbs: 19, fiber: 3.8, vitamins: ["Vit C", "Antioxidants", "Anthocyanins"] },
    seasonality: [5, 6, 7, 8],
    sustainabilityNote: "Avoid air-freighted berries. Buy local and seasonal.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Superfood! Eat seasonal for best impact.",
    waterFootprint: 150
  },
  {
    id: "mango",
    name: "Mango",
    category: "Fruits",
    emoji: "🥭",
    co2PerServing: 0.25,
    servingSize: "1 medium (207g)",
    servingGrams: 207,
    nutrition: { calories: 107, protein: 0.8, fat: 0.3, carbs: 28, fiber: 2.8, vitamins: ["Vit C", "Vit A", "Potassium"] },
    seasonality: [4, 5, 6],
    sustainabilityNote: "Tropical import. Enjoy in moderation.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Delicious but distant. Special treat.",
    waterFootprint: 2200
  },
  {
    id: "strawberry",
    name: "Strawberry",
    category: "Fruits",
    emoji: "🍓",
    co2PerServing: 0.12,
    servingSize: "1 cup (152g)",
    servingGrams: 152,
    nutrition: { calories: 49, protein: 1, fat: 0.5, carbs: 12, fiber: 3, vitamins: ["Vit C", "Manganese", "Folate"] },
    seasonality: [4, 5, 6],
    sustainabilityNote: "Local seasonal berries have minimal impact.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Buy local in season only.",
    waterFootprint: 280
  },
  {
    id: "watermelon",
    name: "Watermelon",
    category: "Fruits",
    emoji: "🍉",
    co2PerServing: 0.05,
    servingSize: "1 cup cubed (152g)",
    servingGrams: 152,
    nutrition: { calories: 46, protein: 0.9, fat: 0.2, carbs: 11, fiber: 0.6, vitamins: ["Vit C", "Lycopene"] },
    seasonality: [6, 7, 8],
    sustainabilityNote: "Summer favorite. 92% water, very low carbon.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Perfect summer hydration.",
    waterFootprint: 240
  },
  {
    id: "grapes",
    name: "Grapes",
    category: "Fruits",
    emoji: "🍇",
    co2PerServing: 0.13,
    servingSize: "1 cup (151g)",
    servingGrams: 151,
    nutrition: { calories: 104, protein: 1.1, fat: 0.2, carbs: 27, fiber: 1.4, vitamins: ["Vit C", "Vit K", "Resveratrol"] },
    seasonality: [8, 9, 10],
    sustainabilityNote: "Can require higher pesticide use. Buy organic when possible.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Excellent antioxidant source.",
    waterFootprint: 608
  },
  {
    id: "pear",
    name: "Pear",
    category: "Fruits",
    emoji: "🍐",
    co2PerServing: 0.05,
    servingSize: "1 medium (178g)",
    servingGrams: 178,
    nutrition: { calories: 101, protein: 0.6, fat: 0.2, carbs: 27, fiber: 6, vitamins: ["Vit C", "Copper", "Boron"] },
    seasonality: [8, 9, 10],
    sustainabilityNote: "Low impact. Great for digestive health.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "High fiber content excellent for digestion.",
    waterFootprint: 70
  },
  {
    id: "peach",
    name: "Peach",
    category: "Fruits",
    emoji: "🍑",
    co2PerServing: 0.06,
    servingSize: "1 medium (150g)",
    servingGrams: 150,
    nutrition: { calories: 59, protein: 1.4, fat: 0.3, carbs: 14, fiber: 2.2, vitamins: ["Vit A", "Vit C", "Potassium"] },
    seasonality: [7, 8, 9],
    sustainabilityNote: "Summer stone fruit. Low impact if local.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Seasonal summer treat.",
    waterFootprint: 910
  },
  {
    id: "kiwi",
    name: "Kiwi",
    category: "Fruits",
    emoji: "🥝",
    co2PerServing: 0.18,
    servingSize: "2 medium (112g)",
    servingGrams: 112,
    nutrition: { calories: 61, protein: 1.1, fat: 0.5, carbs: 15, fiber: 2.4, vitamins: ["Vit C", "Vit E", "Potassium"] },
    seasonality: [10, 11, 0, 1],
    sustainabilityNote: "Tropical but stored well. Higher carbon but nutrient-dense.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Unique nutrient profile.",
    waterFootprint: 600
  },
  {
    id: "avocado",
    name: "Avocado",
    category: "Fruits",
    emoji: "🥑",
    co2PerServing: 0.58,
    servingSize: "1/2 avocado (75g)",
    servingGrams: 75,
    nutrition: { calories: 120, protein: 1.5, fat: 11, carbs: 6, fiber: 5, vitamins: ["Vit E", "Vit K", "Folate"] },
    seasonality: [10, 11, 0, 1, 2],
    sustainabilityNote: "High water use (2200L per 100g). Choose sustainably sourced.",
    ecoScore: "Medium",
    healthScore: "Excellent",
    advice: "Healthy fats but high impact. Use sparingly.",
    waterFootprint: 1650
  },
  {
    id: "pineapple",
    name: "Pineapple",
    category: "Fruits",
    emoji: "🍍",
    co2PerServing: 0.23,
    servingSize: "1 cup chunks (165g)",
    servingGrams: 165,
    nutrition: { calories: 83, protein: 0.9, fat: 0.2, carbs: 22, fiber: 1.4, vitamins: ["Vit C", "Manganese", "Bromelain"] },
    seasonality: [2, 3, 4, 5, 6],
    sustainabilityNote: "Tropical import. Good enzyme content.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Digestive aid. Occasional treat.",
    waterFootprint: 2200
  },
  {
    id: "papaya",
    name: "Papaya",
    category: "Fruits",
    emoji: "🧆",
    co2PerServing: 0.18,
    servingSize: "1 cup (152g)",
    servingGrams: 152,
    nutrition: { calories: 55, protein: 0.9, fat: 0.3, carbs: 14, fiber: 2.5, vitamins: ["Vit C", "Vit A", "Papain"] },
    seasonality: [5, 6, 7, 8],
    sustainabilityNote: "Tropical. Lower impact if from nearby regions.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Digestive enzyme source.",
    waterFootprint: 220
  },
  {
    id: "pomegranate",
    name: "Pomegranate",
    category: "Fruits",
    emoji: "🍎",
    co2PerServing: 0.16,
    servingSize: "1/2 cup seeds (87g)",
    servingGrams: 87,
    nutrition: { calories: 72, protein: 1.5, fat: 0.3, carbs: 16, fiber: 3.7, vitamins: ["Vit C", "Antioxidants", "Punicalagins"] },
    seasonality: [9, 10, 11],
    sustainabilityNote: "Seasonal. Research-backed health benefits.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Super antioxidant powerhouse.",
    waterFootprint: 800
  },
  {
    id: "coconut",
    name: "Coconut",
    category: "Fruits",
    emoji: "🥥",
    co2PerServing: 0.35,
    servingSize: "1 cup shredded (80g)",
    servingGrams: 80,
    nutrition: { calories: 283, protein: 2.7, fat: 27, carbs: 10, fiber: 7.2, vitamins: ["Manganese", "Copper", "MCTs"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Tropical import. Lower impact than other tropical fruits.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Unique fat profile. Moderation advised.",
    waterFootprint: 2687
  },
];

// ===== VEGETABLES (20 items) =====
const vegetableDatabase: FoodItem[] = [
  {
    id: "spinach",
    name: "Spinach",
    category: "Vegetables",
    emoji: "🥬",
    co2PerServing: 0.05,
    servingSize: "1 cup raw (30g)",
    servingGrams: 30,
    nutrition: { calories: 7, protein: 0.9, fat: 0.1, carbs: 1.1, fiber: 0.7, vitamins: ["Vit A", "Vit K", "Iron"] },
    seasonality: [2, 3, 4, 5, 9, 10],
    sustainabilityNote: "Very low impact. Quick-growing crop.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Nutrient-dense superfood.",
    waterFootprint: 240
  },
  {
    id: "kale",
    name: "Kale",
    category: "Vegetables",
    emoji: "🥬",
    co2PerServing: 0.04,
    servingSize: "1 cup chopped (67g)",
    servingGrams: 67,
    nutrition: { calories: 34, protein: 2.2, fat: 0.6, carbs: 7, fiber: 1.3, vitamins: ["Vit K", "Vit A", "Vit C"] },
    seasonality: [9, 10, 11, 0, 1, 2],
    sustainabilityNote: "Cold-hardy. Thrives in cool seasons.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Nutrient powerhouse. Eat raw or cooked.",
    waterFootprint: 237
  },
  {
    id: "broccoli",
    name: "Broccoli",
    category: "Vegetables",
    emoji: "🥦",
    co2PerServing: 0.12,
    servingSize: "1 cup (91g)",
    servingGrams: 91,
    nutrition: { calories: 31, protein: 2.5, fat: 0.3, carbs: 6, fiber: 2.4, vitamins: ["Vit C", "Vit K", "Sulforaphane"] },
    seasonality: [9, 10, 11, 0, 1, 2, 3],
    sustainabilityNote: "Cool season crop. Moderate water use.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Cancer-fighting properties well-researched.",
    waterFootprint: 285
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    category: "Vegetables",
    emoji: "🥬",
    co2PerServing: 0.10,
    servingSize: "1 cup (100g)",
    servingGrams: 100,
    nutrition: { calories: 25, protein: 1.9, fat: 0.3, carbs: 5, fiber: 2.4, vitamins: ["Vit C", "Vit K", "Choline"] },
    seasonality: [9, 10, 11, 0, 1, 2],
    sustainabilityNote: "Versatile and low impact.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Rice substitute or roasted.",
    waterFootprint: 405
  },
  {
    id: "carrot",
    name: "Carrot",
    category: "Vegetables",
    emoji: "🥕",
    co2PerServing: 0.08,
    servingSize: "1 medium (61g)",
    servingGrams: 61,
    nutrition: { calories: 25, protein: 0.6, fat: 0.1, carbs: 6, fiber: 1.7, vitamins: ["Vit A", "Biotin", "Potassium"] },
    seasonality: [8, 9, 10, 11],
    sustainabilityNote: "Storable. Low carbon footprint.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Eye health supporting.",
    waterFootprint: 94
  },
  {
    id: "tomato",
    name: "Tomato",
    category: "Vegetables",
    emoji: "🍅",
    co2PerServing: 0.18,
    servingSize: "1 medium (123g)",
    servingGrams: 123,
    nutrition: { calories: 22, protein: 1.1, fat: 0.2, carbs: 4.8, fiber: 1.5, vitamins: ["Vit C", "Lycopene", "Potassium"] },
    seasonality: [6, 7, 8, 9],
    sustainabilityNote: "Greenhouse tomatoes have higher footprint. Choose field-grown.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Summer favorite. Local preferred.",
    waterFootprint: 214
  },
  {
    id: "cucumber",
    name: "Cucumber",
    category: "Vegetables",
    emoji: "🥒",
    co2PerServing: 0.09,
    servingSize: "1 cup sliced (104g)",
    servingGrams: 104,
    nutrition: { calories: 16, protein: 0.8, fat: 0.2, carbs: 3.6, fiber: 0.5, vitamins: ["Vit K", "Potassium"] },
    seasonality: [6, 7, 8, 9],
    sustainabilityNote: "Summer crop. Mostly water.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Hydrating salad base.",
    waterFootprint: 350
  },
  {
    id: "bell-pepper",
    name: "Bell Pepper",
    category: "Vegetables",
    emoji: "🫑",
    co2PerServing: 0.26,
    servingSize: "1 medium (119g)",
    servingGrams: 119,
    nutrition: { calories: 30, protein: 1, fat: 0.3, carbs: 7, fiber: 1.3, vitamins: ["Vit C", "Vit A", "Antioxidants"] },
    seasonality: [7, 8, 9, 10],
    sustainabilityNote: "Often greenhouse grown. Choose field-grown seasonal.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Colorful = more antioxidants.",
    waterFootprint: 730
  },
  {
    id: "onion",
    name: "Onion",
    category: "Vegetables",
    emoji: "🧅",
    co2PerServing: 0.05,
    servingSize: "1 medium (110g)",
    servingGrams: 110,
    nutrition: { calories: 40, protein: 1.1, fat: 0.1, carbs: 9, fiber: 1.5, vitamins: ["Vit C", "Quercetin"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Excellent storage crop. Year-round staple.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Flavorful and anti-inflammatory.",
    waterFootprint: 232
  },
  {
    id: "garlic",
    name: "Garlic",
    category: "Vegetables",
    emoji: "🧄",
    co2PerServing: 0.05,
    servingSize: "3 cloves (9g)",
    servingGrams: 9,
    nutrition: { calories: 13, protein: 0.6, fat: 0.05, carbs: 3, fiber: 0.2, vitamins: ["Vit C", "Vitamin B6", "Allicin"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Long storage life. Minimal processing needed.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Immune booster. Cooking enhances allicin.",
    waterFootprint: 220
  },
  {
    id: "potato",
    name: "Potato",
    category: "Vegetables",
    emoji: "🥔",
    co2PerServing: 0.03,
    servingSize: "1 medium (173g)",
    servingGrams: 173,
    nutrition: { calories: 161, protein: 4.3, fat: 0.2, carbs: 37, fiber: 3.8, vitamins: ["Vit C", "Vit B6", "Potassium"] },
    seasonality: [8, 9, 10, 11],
    sustainabilityNote: "Highly efficient crop. Stores well.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Keep skin on for fiber.",
    waterFootprint: 287
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    category: "Vegetables",
    emoji: "🍠",
    co2PerServing: 0.05,
    servingSize: "1 medium (100g)",
    servingGrams: 100,
    nutrition: { calories: 86, protein: 1.6, fat: 0.1, carbs: 20, fiber: 3, vitamins: ["Vit A", "Manganese", "Potassium"] },
    seasonality: [9, 10, 11, 0],
    sustainabilityNote: "Nutrient-dense root vegetable. Low impact.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Superior nutritional profile vs white potato.",
    waterFootprint: 360
  },
  {
    id: "lettuce",
    name: "Lettuce",
    category: "Vegetables",
    emoji: "🥬",
    co2PerServing: 0.06,
    servingSize: "2 cups (94g)",
    servingGrams: 94,
    nutrition: { calories: 15, protein: 1.2, fat: 0.2, carbs: 3, fiber: 0.6, vitamins: ["Vit K", "Folate", "Vit A"] },
    seasonality: [3, 4, 5, 6, 9, 10],
    sustainabilityNote: "Spring and fall crop. Low water needs.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Dark leaf varieties are more nutritious.",
    waterFootprint: 237
  },
  {
    id: "cabbage",
    name: "Cabbage",
    category: "Vegetables",
    emoji: "🥬",
    co2PerServing: 0.04,
    servingSize: "1 cup chopped (89g)",
    servingGrams: 89,
    nutrition: { calories: 22, protein: 1.1, fat: 0.1, carbs: 5, fiber: 1.1, vitamins: ["Vit C", "Vit K", "Sulforaphane"] },
    seasonality: [9, 10, 11, 0, 1, 2],
    sustainabilityNote: "Extremely storage-stable. Year-round availability.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Fermented (sauerkraut) adds probiotics.",
    waterFootprint: 237
  },
  {
    id: "zucchini",
    name: "Zucchini",
    category: "Vegetables",
    emoji: "🥒",
    co2PerServing: 0.08,
    servingSize: "1 cup sliced (124g)",
    servingGrams: 124,
    nutrition: { calories: 21, protein: 1.4, fat: 0.4, carbs: 3.5, fiber: 1, vitamins: ["Vit C", "Vit A", "Manganese"] },
    seasonality: [6, 7, 8, 9],
    sustainabilityNote: "Summer squash. Prolific producer.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Versatile recipe ingredient.",
    waterFootprint: 384
  },
  {
    id: "celery",
    name: "Celery",
    category: "Vegetables",
    emoji: "🥒",
    co2PerServing: 0.07,
    servingSize: "1 stalk (40g)",
    servingGrams: 40,
    nutrition: { calories: 6, protein: 0.3, fat: 0.1, carbs: 1.2, fiber: 0.6, vitamins: ["Vit K", "Potassium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Available year-round. Crunchy and hydrating.",
    ecoScore: "Low",
    healthScore: "Moderate",
    advice: "Perfect vegetable for snacking.",
    waterFootprint: 285
  },
  {
    id: "asparagus",
    name: "Asparagus",
    category: "Vegetables",
    emoji: "🥒",
    co2PerServing: 0.06,
    servingSize: "6 spears (90g)",
    servingGrams: 90,
    nutrition: { calories: 20, protein: 2.2, fat: 0.1, carbs: 3.7, fiber: 2.1, vitamins: ["Vit K", "Folate", "Glutathione"] },
    seasonality: [3, 4, 5],
    sustainabilityNote: "Spring delicacy. Needs specific conditions.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Detoxification supporter.",
    waterFootprint: 1509
  },
  {
    id: "mushroom",
    name: "Mushroom",
    category: "Vegetables",
    emoji: "🍄",
    co2PerServing: 0.09,
    servingSize: "1 cup (70g)",
    servingGrams: 70,
    nutrition: { calories: 15, protein: 2.2, fat: 0.3, carbs: 2.3, fiber: 0.4, vitamins: ["Vit D", "Selenium", "B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Can be grown on agricultural waste. Highly sustainable.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Nature's immune booster.",
    waterFootprint: 99
  },
  {
    id: "peas",
    name: "Peas",
    category: "Vegetables",
    emoji: "🫘",
    co2PerServing: 0.08,
    servingSize: "1 cup (160g)",
    servingGrams: 160,
    nutrition: { calories: 134, protein: 9, fat: 0.4, carbs: 25, fiber: 9, vitamins: ["Vit C", "Vit K", "Manganese"] },
    seasonality: [4, 5, 6],
    sustainabilityNote: "Nitrogen-fixing crop. Benefits soil.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Complete plant protein source.",
    waterFootprint: 2497
  },
  {
    id: "corn",
    name: "Corn",
    category: "Vegetables",
    emoji: "🌽",
    co2PerServing: 0.17,
    servingSize: "1 ear (77g)",
    servingGrams: 77,
    nutrition: { calories: 77, protein: 2.9, fat: 1.2, carbs: 17, fiber: 2.4, vitamins: ["Vit C", "Thiamine", "Pantothenic Acid"] },
    seasonality: [7, 8, 9],
    sustainabilityNote: "Often GMO and heavily sprayed. Choose organic.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Organic or local varieties preferred.",
    waterFootprint: 1423
  },
];

// ===== GRAINS & CEREALS (12 items) =====
const grainsDatabase: FoodItem[] = [
  {
    id: "rice-brown",
    name: "Brown Rice",
    category: "Grains & Cereals",
    emoji: "🍚",
    co2PerServing: 0.45,
    servingSize: "1 cup cooked (195g)",
    servingGrams: 195,
    nutrition: { calories: 215, protein: 5, fat: 1.8, carbs: 45, fiber: 3.5, vitamins: ["Manganese", "B Vitamins", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Lower carbon than white rice. Choose short-grain.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Keep the bran for nutrients and fiber.",
    waterFootprint: 2810
  },
  {
    id: "rice-white",
    name: "White Rice",
    category: "Grains & Cereals",
    emoji: "🍚",
    co2PerServing: 0.60,
    servingSize: "1 cup cooked (158g)",
    servingGrams: 158,
    nutrition: { calories: 205, protein: 4.3, fat: 0.4, carbs: 45, fiber: 0.6, vitamins: ["Thiamine", "B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "High methane emissions from paddies. Consider alternatives.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Choose brown rice when possible.",
    waterFootprint: 3000
  },
  {
    id: "oats",
    name: "Oats",
    category: "Grains & Cereals",
    emoji: "🥣",
    co2PerServing: 0.18,
    servingSize: "1/2 cup dry (40g)",
    servingGrams: 40,
    nutrition: { calories: 150, protein: 5, fat: 3, carbs: 27, fiber: 4, vitamins: ["Manganese", "Phosphorus", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Excellent crop for soil health.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Cholesterol-reducing benefits.",
    waterFootprint: 305
  },
  {
    id: "quinoa",
    name: "Quinoa",
    category: "Grains & Cereals",
    emoji: "🌾",
    co2PerServing: 0.85,
    servingSize: "1 cup cooked (185g)",
    servingGrams: 185,
    nutrition: { calories: 222, protein: 8, fat: 4, carbs: 39, fiber: 5, vitamins: ["Manganese", "Phosphorus", "Folate"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Trendy superfood. High carbon due to air-freight.",
    ecoScore: "High",
    healthScore: "Excellent",
    advice: "Contains all amino acids but high impact.",
    waterFootprint: 1790
  },
  {
    id: "wheat",
    name: "Wheat (Whole)",
    category: "Grains & Cereals",
    emoji: "🌾",
    co2PerServing: 0.12,
    servingSize: "1 cup cooked (240g)",
    servingGrams: 240,
    nutrition: { calories: 251, protein: 11, fat: 2, carbs: 53, fiber: 8, vitamins: ["Manganese", "B Vitamins", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Local grain. Choose heritage varieties.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Whole grains superior nutrition.",
    waterFootprint: 540
  },
  {
    id: "barley",
    name: "Barley",
    category: "Grains & Cereals",
    emoji: "🌾",
    co2PerServing: 0.10,
    servingSize: "1 cup cooked (200g)",
    servingGrams: 200,
    nutrition: { calories: 193, protein: 7, fat: 1.5, carbs: 44, fiber: 6, vitamins: ["Manganese", "Phosphorus", "Copper"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Resilient crop. Low carbon footprint.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Beta-glucans support heart health.",
    waterFootprint: 525
  },
  {
    id: "millet",
    name: "Millet",
    category: "Grains & Cereals",
    emoji: "🌾",
    co2PerServing: 0.08,
    servingSize: "1 cup cooked (200g)",
    servingGrams: 200,
    nutrition: { calories: 207, protein: 6, fat: 1.7, carbs: 41, fiber: 2.3, vitamins: ["Magnesium", "Manganese", "Phosphorus"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Ancient grain. Drought-resistant.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Gluten-free option.",
    waterFootprint: 410
  },
  {
    id: "rye",
    name: "Rye",
    category: "Grains & Cereals",
    emoji: "🌾",
    co2PerServing: 0.11,
    servingSize: "1 slice bread (32g)",
    servingGrams: 32,
    nutrition: { calories: 83, protein: 2.7, fat: 0.6, carbs: 15.5, fiber: 2.4, vitamins: ["Manganese", "Phosphorus"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Hardy grain. Low input needs.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Lower glycemic index.",
    waterFootprint: 305
  },
  {
    id: "buckwheat",
    name: "Buckwheat",
    category: "Grains & Cereals",
    emoji: "🌾",
    co2PerServing: 0.14,
    servingSize: "1 cup cooked (168g)",
    servingGrams: 168,
    nutrition: { calories: 155, protein: 6, fat: 1, carbs: 33, fiber: 4.5, vitamins: ["Manganese", "Copper", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Gluten-free pseudo-grain. Bee-friendly crop.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Complete protein. Soba noodles option.",
    waterFootprint: 595
  },
  {
    id: "corn-meal",
    name: "Cornmeal",
    category: "Grains & Cereals",
    emoji: "🌽",
    co2PerServing: 0.19,
    servingSize: "1/4 cup dry (34g)",
    servingGrams: 34,
    nutrition: { calories: 127, protein: 2, fat: 0.9, carbs: 28, fiber: 2.3, vitamins: ["B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Often genetically modified. Choose organic.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Choose heritage varieties when possible.",
    waterFootprint: 790
  },
  {
    id: "bread-white",
    name: "Bread (White)",
    category: "Grains & Cereals",
    emoji: "🍞",
    co2PerServing: 0.25,
    servingSize: "1 slice (28g)",
    servingGrams: 28,
    nutrition: { calories: 75, protein: 2.7, fat: 0.9, carbs: 14, fiber: 0.6, vitamins: ["B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Refined grains. Whole wheat preferred.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Choose whole grain varieties.",
    waterFootprint: 240
  },
  {
    id: "bread-whole",
    name: "Bread (Whole Wheat)",
    category: "Grains & Cereals",
    emoji: "🍞",
    co2PerServing: 0.21,
    servingSize: "1 slice (28g)",
    servingGrams: 28,
    nutrition: { calories: 80, protein: 4, fat: 1.2, carbs: 14, fiber: 2.4, vitamins: ["B Vitamins", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Better than white. Support local bakeries.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Fiber-rich option for sustained energy.",
    waterFootprint: 193
  }
];

// ===== LEGUMES & PULSES (8 items) =====
const legumesDatabase: FoodItem[] = [
  {
    id: "lentils",
    name: "Lentils",
    category: "Legumes & Pulses",
    emoji: "🫘",
    co2PerServing: 0.05,
    servingSize: "1 cup cooked (198g)",
    servingGrams: 198,
    nutrition: { calories: 230, protein: 18, fat: 0.8, carbs: 40, fiber: 16, vitamins: ["Iron", "Folate", "Polyphenols"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Nitrogen-fixing. Improves soil quality.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Perfect protein for vegans/vegetarians.",
    waterFootprint: 4000
  },
  {
    id: "chickpeas",
    name: "Chickpeas",
    category: "Legumes & Pulses",
    emoji: "🫘",
    co2PerServing: 0.06,
    servingSize: "1 cup cooked (164g)",
    servingGrams: 164,
    nutrition: { calories: 269, protein: 14.5, fat: 4, carbs: 45, fiber: 12.5, vitamins: ["Manganese", "Folate", "Iron"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Drought-resistant legume.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Versatile: hummus, curry, salad.",
    waterFootprint: 4400
  },
  {
    id: "black-beans",
    name: "Black Beans",
    category: "Legumes & Pulses",
    emoji: "🫘",
    co2PerServing: 0.07,
    servingSize: "1 cup cooked (172g)",
    servingGrams: 172,
    nutrition: { calories: 227, protein: 15, fat: 0.9, carbs: 41, fiber: 15, vitamins: ["Folate", "Iron", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Nitrogen-fixing crop.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Latin American staple.",
    waterFootprint: 3350
  },
  {
    id: "kidney-beans",
    name: "Kidney Beans",
    category: "Legumes & Pulses",
    emoji: "🫘",
    co2PerServing: 0.07,
    servingSize: "1 cup cooked (177g)",
    servingGrams: 177,
    nutrition: { calories: 225, protein: 15, fat: 0.8, carbs: 40, fiber: 11, vitamins: ["Folate", "Iron", "Manganese"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Versatile legume crop.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Great in chili and soups.",
    waterFootprint: 4044
  },
  {
    id: "peanuts",
    name: "Peanuts",
    category: "Legumes & Pulses",
    emoji: "🥜",
    co2PerServing: 0.10,
    servingSize: "1 oz (28g)",
    servingGrams: 28,
    nutrition: { calories: 161, protein: 7.3, fat: 14, carbs: 4.6, fiber: 2.5, vitamins: ["Vit E", "Folate", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Legume technically. Check for pesticides.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Excellent protein and healthy fats.",
    waterFootprint: 7600
  },
  {
    id: "tofu",
    name: "Tofu",
    category: "Legumes & Pulses",
    emoji: "🟫",
    co2PerServing: 0.15,
    servingSize: "1/2 cup (126g)",
    servingGrams: 126,
    nutrition: { calories: 94, protein: 10, fat: 5.9, carbs: 1.6, fiber: 0.6, vitamins: ["Iron", "Calcium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Soy from diverse sources. Look for non-GMO/sustainable.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Complete protein. Choose organic.",
    waterFootprint: 1600
  },
  {
    id: "tempeh",
    name: "Tempeh",
    category: "Legumes & Pulses",
    emoji: "🟫",
    co2PerServing: 0.14,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 95, protein: 11, fat: 5, carbs: 3, fiber: 1.4, vitamins: ["B Vitamins", "Iron", "Manganese"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Fermented soy. Good bioavailability.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Superior to tofu. Better texture.",
    waterFootprint: 1430
  },
  {
    id: "edamame",
    name: "Edamame",
    category: "Legumes & Pulses",
    emoji: "🫘",
    co2PerServing: 0.12,
    servingSize: "1 cup (155g)",
    servingGrams: 155,
    nutrition: { calories: 189, protein: 17, fat: 8, carbs: 13, fiber: 8, vitamins: ["Vit K", "Iron", "Manganese"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Young soybean. Nutritious legume.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Complete plant protein.",
    waterFootprint: 2400
  }
];

// ===== DAIRY & ALTERNATIVES (10 items) =====
const dairyDatabase: FoodItem[] = [
  {
    id: "milk",
    name: "Dairy Milk",
    category: "Dairy & Alternatives",
    emoji: "🥛",
    co2PerServing: 0.76,
    servingSize: "1 cup (244g)",
    servingGrams: 244,
    nutrition: { calories: 149, protein: 8, fat: 8, carbs: 12, fiber: 0, vitamins: ["Calcium", "Vit D", "B12"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "High water and methane emissions. Plant alternatives are better.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Consider plant-based alternatives.",
    waterFootprint: 628
  },
  {
    id: "almond-milk",
    name: "Almond Milk",
    category: "Dairy & Alternatives",
    emoji: "🥛",
    co2PerServing: 0.07,
    servingSize: "1 cup (240g)",
    servingGrams: 240,
    nutrition: { calories: 30, protein: 1, fat: 2.5, carbs: 1, fiber: 0, vitamins: ["Vit E", "Calcium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Lower carbon but water-intensive (California). Coconut/oat better.",
    ecoScore: "Low",
    healthScore: "Moderate",
    advice: "Choose fortified versions.",
    waterFootprint: 371
  },
  {
    id: "oat-milk",
    name: "Oat Milk",
    category: "Dairy & Alternatives",
    emoji: "🥛",
    co2PerServing: 0.09,
    servingSize: "1 cup (240g)",
    servingGrams: 240,
    nutrition: { calories: 120, protein: 2.7, fat: 5, carbs: 16, fiber: 0, vitamins: ["Calcium", "B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Lower carbon than dairy. Most sustainable plant milk option.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Best plant-based option overall.",
    waterFootprint: 48
  },
  {
    id: "coconut-milk",
    name: "Coconut Milk",
    category: "Dairy & Alternatives",
    emoji: "🥥",
    co2PerServing: 0.35,
    servingSize: "1 cup (240g)",
    servingGrams: 240,
    nutrition: { calories: 560, protein: 5, fat: 57, carbs: 6, fiber: 0, vitamins: ["Manganese", "Copper"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Higher fat. Use in moderation.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Good for cooking. Limit as drink.",
    waterFootprint: 2687
  },
  {
    id: "soy-milk",
    name: "Soy Milk",
    category: "Dairy & Alternatives",
    emoji: "🥛",
    co2PerServing: 0.15,
    servingSize: "1 cup (240g)",
    servingGrams: 240,
    nutrition: { calories: 80, protein: 7, fat: 4, carbs: 4, fiber: 0, vitamins: ["B12", "Calcium", "Iron"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Complete protein. Choose organic/non-GMO.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Complete plant protein.",
    waterFootprint: 1600
  },
  {
    id: "yogurt",
    name: "Yogurt (Dairy)",
    category: "Dairy & Alternatives",
    emoji: "🥛",
    co2PerServing: 0.43,
    servingSize: "1 cup (227g)",
    servingGrams: 227,
    nutrition: { calories: 149, protein: 17, fat: 5, carbs: 11, fiber: 0, vitamins: ["Calcium", "Probiotics", "B12"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Probiotics support health. Choose local.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Good protein and probiotics.",
    waterFootprint: 1500
  },
  {
    id: "cheese",
    name: "Cheese",
    category: "Dairy & Alternatives",
    emoji: "🧀",
    co2PerServing: 1.15,
    servingSize: "1.5 oz (42g)",
    servingGrams: 42,
    nutrition: { calories: 170, protein: 10, fat: 14, carbs: 1, fiber: 0, vitamins: ["Calcium", "Vit A", "B12"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "High carbon and water use. Enjoy sparingly.",
    ecoScore: "High",
    healthScore: "Moderate",
    advice: "Limit portion sizes.",
    waterFootprint: 710
  },
  {
    id: "butter",
    name: "Butter",
    category: "Dairy & Alternatives",
    emoji: "🧈",
    co2PerServing: 1.23,
    servingSize: "1 tbsp (14g)",
    servingGrams: 14,
    nutrition: { calories: 102, protein: 0.1, fat: 11.5, carbs: 0, fiber: 0, vitamins: ["Vit A", "Vit E"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Dairy product. Plant oils have lower impact.",
    ecoScore: "High",
    healthScore: "Moderate",
    advice: "Use plant oils instead.",
    waterFootprint: 575
  },
  {
    id: "cottage-cheese",
    name: "Cottage Cheese",
    category: "Dairy & Alternatives",
    emoji: "🥛",
    co2PerServing: 0.37,
    servingSize: "1 cup (225g)",
    servingGrams: 225,
    nutrition: { calories: 206, protein: 28, fat: 9, carbs: 7, fiber: 0, vitamins: ["Calcium", "Selenium", "B12"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Whey-based product. High protein.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Excellent protein source.",
    waterFootprint: 1080
  },
  {
    id: "greek-yogurt",
    name: "Greek Yogurt",
    category: "Dairy & Alternatives",
    emoji: "🥛",
    co2PerServing: 0.48,
    servingSize: "1 cup (227g)",
    servingGrams: 227,
    nutrition: { calories: 220, protein: 20, fat: 10, carbs: 9, fiber: 0, vitamins: ["Calcium", "Probiotics", "B12"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Strained yogurt. Higher protein concentration.",
    ecoScore: "Medium",
    healthScore: "Excellent",
    advice: "High protein and probiotics.",
    waterFootprint: 1500
  }
];

// ===== MEAT & PROTEIN (8 items) =====
const meatDatabase: FoodItem[] = [
  {
    id: "beef",
    name: "Beef",
    category: "Meat & Protein",
    emoji: "🥩",
    co2PerServing: 6.61,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 213, protein: 22, fat: 13, carbs: 0, fiber: 0, vitamins: ["B12", "Iron", "Zinc", "Niacin"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Highest carbon footprint. Limit consumption significantly.",
    ecoScore: "High",
    healthScore: "Moderate",
    advice: "Reduce or eliminate for environmental impact.",
    waterFootprint: 15000
  },
  {
    id: "chicken",
    name: "Chicken",
    category: "Meat & Protein",
    emoji: "🍗",
    co2PerServing: 0.58,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 122, protein: 23, fat: 3, carbs: 0, fiber: 0, vitamins: ["B6", "Niacin", "Selenium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Lower impact than beef. Choose pasture-raised when possible.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Better choice than beef but reduce overall.",
    waterFootprint: 4325
  },
  {
    id: "turkey",
    name: "Turkey",
    category: "Meat & Protein",
    emoji: "🦃",
    co2PerServing: 0.39,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 135, protein: 26, fat: 3, carbs: 0, fiber: 0, vitamins: ["Selenium", "B6", "Niacin"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Lower carbon than chicken. Leaner meat.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Good poultry option.",
    waterFootprint: 3100
  },
  {
    id: "fish-salmon",
    name: "Salmon",
    category: "Meat & Protein",
    emoji: "🐟",
    co2PerServing: 2.15,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 175, protein: 19, fat: 10, carbs: 0, fiber: 0, vitamins: ["Omega-3", "Vit D", "Selenium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Farmed salmon has moderate impact. Choose wild when possible.",
    ecoScore: "Medium",
    healthScore: "Excellent",
    advice: "Rich in omega-3s but choose wild-caught.",
    waterFootprint: 3000
  },
  {
    id: "fish-tuna",
    name: "Tuna",
    category: "Meat & Protein",
    emoji: "🐟",
    co2PerServing: 1.52,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 133, protein: 22, fat: 4.6, carbs: 0, fiber: 0, vitamins: ["Omega-3", "Selenium", "Niacin"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Overfishing concerns. Choose sustainably-caught.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Limit to reduce mercury exposure.",
    waterFootprint: 2400
  },
  {
    id: "eggs",
    name: "Eggs",
    category: "Meat & Protein",
    emoji: "🥚",
    co2PerServing: 0.37,
    servingSize: "1 large (50g)",
    servingGrams: 50,
    nutrition: { calories: 78, protein: 6, fat: 5.3, carbs: 0.6, fiber: 0, vitamins: ["Choline", "Lutein", "B12"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Pasture-raised eggs are better. Lower carbon than meat.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Choose pasture-raised or free-range.",
    waterFootprint: 196
  },
  {
    id: "pork",
    name: "Pork",
    category: "Meat & Protein",
    emoji: "🍖",
    co2PerServing: 1.89,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 137, protein: 23, fat: 5, carbs: 0, fiber: 0, vitamins: ["B6", "Niacin", "Selenium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Moderate impact. Better than beef, not as good as fish.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Choose lean cuts.",
    waterFootprint: 5987
  },
  {
    id: "shrimp",
    name: "Shrimp",
    category: "Meat & Protein",
    emoji: "🦐",
    co2PerServing: 2.73,
    servingSize: "3 oz (85g)",
    servingGrams: 85,
    nutrition: { calories: 99, protein: 24, fat: 0.3, carbs: 0, fiber: 0, vitamins: ["Selenium", "Vit B12"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "High carbon despite low weight. Farming impacts ecosystems.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "High protein but environmental concerns.",
    waterFootprint: 7200
  }
];

// ===== NUTS & SEEDS (8 items) =====
const nutsDatabase: FoodItem[] = [
  {
    id: "almonds",
    name: "Almonds",
    category: "Nuts & Seeds",
    emoji: "🌰",
    co2PerServing: 0.05,
    servingSize: "1 oz (28g)",
    servingGrams: 28,
    nutrition: { calories: 164, protein: 6, fat: 14, carbs: 6, fiber: 3.5, vitamins: ["Vit E", "Magnesium", "Copper"] },
    seasonality: [8, 9, 10],
    sustainabilityNote: "Water-intensive in California. Trees are carbon-negative.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Nutrient-dense snack.",
    waterFootprint: 2800
  },
  {
    id: "walnuts",
    name: "Walnuts",
    category: "Nuts & Seeds",
    emoji: "🌰",
    co2PerServing: 0.04,
    servingSize: "1 oz (28g)",
    servingGrams: 28,
    nutrition: { calories: 185, protein: 4, fat: 18, carbs: 4, fiber: 2, vitamins: ["Omega-3", "Copper", "Manganese"] },
    seasonality: [9, 10],
    sustainabilityNote: "Excellent for carbon sequestration.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Best nut for brain health.",
    waterFootprint: 3900
  },
  {
    id: "peanuts",
    name: "Peanuts",
    category: "Nuts & Seeds",
    emoji: "🥜",
    co2PerServing: 0.10,
    servingSize: "1 oz (28g)",
    servingGrams: 28,
    nutrition: { calories: 161, protein: 7.3, fat: 14, carbs: 4.6, fiber: 2.5, vitamins: ["Vit E", "Folate", "Niacin"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Legume technically. Lower impact.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Excellent protein snack.",
    waterFootprint: 2700
  },
  {
    id: "cashews",
    name: "Cashews",
    category: "Nuts & Seeds",
    emoji: "🌰",
    co2PerServing: 0.15,
    servingSize: "1 oz (28g)",
    servingGrams: 28,
    nutrition: { calories: 155, protein: 5, fat: 12, carbs: 9, fiber: 0.9, vitamins: ["Copper", "Manganese", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Tropical. Moderate carbon.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Creamy texture for sauces.",
    waterFootprint: 3500
  },
  {
    id: "sunflower-seeds",
    name: "Sunflower Seeds",
    category: "Nuts & Seeds",
    emoji: "🌻",
    co2PerServing: 0.06,
    servingSize: "1/4 cup (34g)",
    servingGrams: 34,
    nutrition: { calories: 193, protein: 6.5, fat: 17, carbs: 7, fiber: 2.4, vitamins: ["Vit E", "Selenium", "Copper"] },
    seasonality: [8, 9, 10],
    sustainabilityNote: "Local crop in many regions.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Great source of Vitamin E.",
    waterFootprint: 800
  },
  {
    id: "flax-seeds",
    name: "Flax Seeds",
    category: "Nuts & Seeds",
    emoji: "🌿",
    co2PerServing: 0.04,
    servingSize: "1 tbsp (10g)",
    servingGrams: 10,
    nutrition: { calories: 55, protein: 1.9, fat: 4.3, carbs: 3, fiber: 2.8, vitamins: ["Omega-3", "Lignans"] },
    seasonality: [7, 8, 9],
    sustainabilityNote: "Low-impact local crop.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Ground flax for better absorption.",
    waterFootprint: 167
  },
  {
    id: "chia-seeds",
    name: "Chia Seeds",
    category: "Nuts & Seeds",
    emoji: "🌿",
    co2PerServing: 0.23,
    servingSize: "1 tbsp (15g)",
    servingGrams: 15,
    nutrition: { calories: 69, protein: 2.2, fat: 4.3, carbs: 6, fiber: 4.9, vitamins: ["Omega-3", "Calcium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Tropical origin. High carbon due to air freight.",
    ecoScore: "Medium",
    healthScore: "Excellent",
    advice: "Trendy superfood but high carbon.",
    waterFootprint: 1524
  },
  {
    id: "hemp-seeds",
    name: "Hemp Seeds",
    category: "Nuts & Seeds",
    emoji: "🌿",
    co2PerServing: 0.08,
    servingSize: "3 tbsp (30g)",
    servingGrams: 30,
    nutrition: { calories: 161, protein: 9.2, fat: 12, carbs: 2.6, fiber: 1.2, vitamins: ["Omega-3", "Magnesium"] },
    seasonality: [5, 6, 7],
    sustainabilityNote: "Sustainable crop. Complete protein.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Complete plant protein.",
    waterFootprint: 1414
  }
];

// ===== OILS & FATS (5 items) =====
const oilsDatabase: FoodItem[] = [
  {
    id: "olive-oil",
    name: "Olive Oil",
    category: "Oils & Fats",
    emoji: "🫒",
    co2PerServing: 0.20,
    servingSize: "1 tbsp (15ml)",
    servingGrams: 14,
    nutrition: { calories: 120, protein: 0, fat: 14, carbs: 0, fiber: 0, vitamins: ["Vit E", "Polyphenols"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Medium carbon. Choose local.",
    ecoScore: "Medium",
    healthScore: "Excellent",
    advice: "Best oil for health.",
    waterFootprint: 1500
  },
  {
    id: "coconut-oil",
    name: "Coconut Oil",
    category: "Oils & Fats",
    emoji: "🥥",
    co2PerServing: 0.35,
    servingSize: "1 tbsp (15ml)",
    servingGrams: 14,
    nutrition: { calories: 117, protein: 0, fat: 13.5, carbs: 0, fiber: 0, vitamins: ["MCTs"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Tropical. High fat content.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Use sparingly despite hype.",
    waterFootprint: 2687
  },
  {
    id: "canola-oil",
    name: "Canola Oil",
    category: "Oils & Fats",
    emoji: "🫒",
    co2PerServing: 0.16,
    servingSize: "1 tbsp (15ml)",
    servingGrams: 14,
    nutrition: { calories: 120, protein: 0, fat: 14, carbs: 0, fiber: 0, vitamins: ["Omega-3s"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Often GMO. Choose organic/non-GMO.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "High heat cooking oil.",
    waterFootprint: 860
  },
  {
    id: "avocado-oil",
    name: "Avocado Oil",
    category: "Oils & Fats",
    emoji: "🥑",
    co2PerServing: 0.58,
    servingSize: "1 tbsp (15ml)",
    servingGrams: 14,
    nutrition: { calories: 120, protein: 0, fat: 14, carbs: 0, fiber: 0, vitamins: ["Vit E", "Lutein"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "High water footprint of source fruit.",
    ecoScore: "Medium",
    healthScore: "Excellent",
    advice: "Healthy but high impact.",
    waterFootprint: 1650
  },
  {
    id: "sunflower-oil",
    name: "Sunflower Oil",
    category: "Oils & Fats",
    emoji: "🌻",
    co2PerServing: 0.08,
    servingSize: "1 tbsp (15ml)",
    servingGrams: 14,
    nutrition: { calories: 120, protein: 0, fat: 14, carbs: 0, fiber: 0, vitamins: ["Vit E", "Linoleic acid"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Local crop in many areas.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Low carbon local option.",
    waterFootprint: 450
  }
];

// ===== BEVERAGES (6 items) =====
const beveragesDatabase: FoodItem[] = [
  {
    id: "water",
    name: "Water (Tap)",
    category: "Beverages",
    emoji: "💧",
    co2PerServing: 0.0,
    servingSize: "1 cup (240ml)",
    servingGrams: 240,
    nutrition: { calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, vitamins: [] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Zero carbon. The best choice.",
    ecoScore: "Low",
    healthScore: "Excellent",
    advice: "Always choose tap over bottled.",
    waterFootprint: 0
  },
  {
    id: "coffee",
    name: "Coffee",
    category: "Beverages",
    emoji: "☕",
    co2PerServing: 0.48,
    servingSize: "1 cup (240ml)",
    servingGrams: 240,
    nutrition: { calories: 2, protein: 0.3, fat: 0, carbs: 0, fiber: 0, vitamins: ["Antioxidants"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Choose fair-trade, shade-grown when possible.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Choose sustainable sources.",
    waterFootprint: 140
  },
  {
    id: "tea",
    name: "Tea",
    category: "Beverages",
    emoji: "🍵",
    co2PerServing: 0.08,
    servingSize: "1 cup (240ml)",
    servingGrams: 240,
    nutrition: { calories: 2, protein: 0, fat: 0, carbs: 0.7, fiber: 0, vitamins: ["Antioxidants"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Lower impact than coffee.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Excellent low-carbon choice.",
    waterFootprint: 27
  },
  {
    id: "orange-juice",
    name: "Orange Juice",
    category: "Beverages",
    emoji: "🍊",
    co2PerServing: 0.27,
    servingSize: "1 cup (240ml)",
    servingGrams: 240,
    nutrition: { calories: 112, protein: 1.7, fat: 0.5, carbs: 26, fiber: 0.5, vitamins: ["Vit C"] },
    seasonality: [11, 0, 1, 2, 3],
    sustainabilityNote: "High water footprint. Eat whole fruit instead.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Eat whole fruit for fiber.",
    waterFootprint: 860
  },
  {
    id: "almond-milk",
    name: "Almond Milk (Beverage)",
    category: "Beverages",
    emoji: "🥛",
    co2PerServing: 0.07,
    servingSize: "1 cup (240ml)",
    servingGrams: 240,
    nutrition: { calories: 30, protein: 1, fat: 2.5, carbs: 1, fiber: 0, vitamins: ["Vit E", "Calcium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Low carbon alternative to dairy.",
    ecoScore: "Low",
    healthScore: "Moderate",
    advice: "Good dairy alternative.",
    waterFootprint: 371
  },
  {
    id: "wine-red",
    name: "Wine (Red)",
    category: "Beverages",
    emoji: "🍷",
    co2PerServing: 0.30,
    servingSize: "5 oz (150ml)",
    servingGrams: 150,
    nutrition: { calories: 125, protein: 0.1, fat: 0, carbs: 3.8, fiber: 0, vitamins: ["Resveratrol", "Polyphenols"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Choose organic/biodynamic. Moderate consumption.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Moderate consumption only.",
    waterFootprint: 840
  }
];

// ===== SNACKS & OTHERS (9 items) =====
const snacksDatabase: FoodItem[] = [
  {
    id: "dark-chocolate",
    name: "Dark Chocolate",
    category: "Snacks & Others",
    emoji: "🍫",
    co2PerServing: 0.44,
    servingSize: "1 oz (28g)",
    servingGrams: 28,
    nutrition: { calories: 168, protein: 2, fat: 12, carbs: 16, fiber: 2.4, vitamins: ["Antioxidants", "Iron"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Choose fair-trade. High carbon from cocoa.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Occasional treat. Choose fair-trade.",
    waterFootprint: 2400
  },
  {
    id: "hummus",
    name: "Hummus",
    category: "Snacks & Others",
    emoji: "🥜",
    co2PerServing: 0.08,
    servingSize: "1/4 cup (61g)",
    servingGrams: 61,
    nutrition: { calories: 99, protein: 2.9, fat: 5, carbs: 10, fiber: 2, vitamins: ["Iron", "Copper"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Chickpea-based. Highly sustainable.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Perfect dip for vegetables.",
    waterFootprint: 627
  },
  {
    id: "popcorn",
    name: "Popcorn",
    category: "Snacks & Others",
    emoji: "🍿",
    co2PerServing: 0.19,
    servingSize: "3 cups (24g)",
    servingGrams: 24,
    nutrition: { calories: 94, protein: 3, fat: 1, carbs: 19, fiber: 3.5, vitamins: ["Manganese"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Low-impact grain snack.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Air-popped is best.",
    waterFootprint: 1700
  },
  {
    id: "granola",
    name: "Granola",
    category: "Snacks & Others",
    emoji: "🥣",
    co2PerServing: 0.22,
    servingSize: "1/2 cup (60g)",
    servingGrams: 60,
    nutrition: { calories: 267, protein: 7, fat: 9, carbs: 38, fiber: 4, vitamins: ["Manganese", "B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Check ingredients. Homemade is better.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Watch portion sizes.",
    waterFootprint: 850
  },
  {
    id: "trail-mix",
    name: "Trail Mix",
    category: "Snacks & Others",
    emoji: "🥜",
    co2PerServing: 0.12,
    servingSize: "1/4 cup (34g)",
    servingGrams: 34,
    nutrition: { calories: 153, protein: 5, fat: 10, carbs: 13, fiber: 2.5, vitamins: ["Vit E", "Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Homemade with local nuts preferred.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Make your own for best control.",
    waterFootprint: 1500
  },
  {
    id: "yogurt-greek",
    name: "Greek Yogurt (Snack)",
    category: "Snacks & Others",
    emoji: "🥛",
    co2PerServing: 0.48,
    servingSize: "5.3 oz (150g)",
    servingGrams: 150,
    nutrition: { calories: 146, protein: 20, fat: 4, carbs: 6, fiber: 0, vitamins: ["Calcium", "Probiotics"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Protein-rich dairy. Use plant-based alternatives.",
    ecoScore: "Medium",
    healthScore: "Good",
    advice: "Good protein but dairy-heavy.",
    waterFootprint: 1500
  },
  {
    id: "protein-bar",
    name: "Protein Bar",
    category: "Snacks & Others",
    emoji: "🍫",
    co2PerServing: 0.35,
    servingSize: "1 bar (50g)",
    servingGrams: 50,
    nutrition: { calories: 200, protein: 20, fat: 7, carbs: 12, fiber: 3, vitamins: ["B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Highly processed. Check ingredients.",
    ecoScore: "Medium",
    healthScore: "Moderate",
    advice: "Occasional convenience food.",
    waterFootprint: 2000
  },
  {
    id: "crackers",
    name: "Whole Grain Crackers",
    category: "Snacks & Others",
    emoji: "🥣",
    co2PerServing: 0.18,
    servingSize: "7 crackers (28g)",
    servingGrams: 28,
    nutrition: { calories: 120, protein: 3, fat: 3.5, carbs: 19, fiber: 3, vitamins: ["B Vitamins"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Whole grain option preferred.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Better with vegetable toppings.",
    waterFootprint: 540
  },
  {
    id: "energy-ball",
    name: "Energy Ball (Homemade)",
    category: "Snacks & Others",
    emoji: "🍫",
    co2PerServing: 0.10,
    servingSize: "1 ball (20g)",
    servingGrams: 20,
    nutrition: { calories: 80, protein: 2, fat: 5, carbs: 8, fiber: 1.5, vitamins: ["Magnesium"] },
    seasonality: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    sustainabilityNote: "Make with local nuts and dates.",
    ecoScore: "Low",
    healthScore: "Good",
    advice: "Best made at home.",
    waterFootprint: 600
  }
];

// Combine all food databases
export const foodDatabase: FoodItem[] = [
  ...fruitDatabase,
  ...vegetableDatabase,
  ...grainsDatabase,
  ...legumesDatabase,
  ...dairyDatabase,
  ...meatDatabase,
  ...nutsDatabase,
  ...oilsDatabase,
  ...beveragesDatabase,
  ...snacksDatabase,
];

// Get all unique categories
export const getAllCategories = (): FoodCategory[] => {
  const categories = new Set<FoodCategory>();
  foodDatabase.forEach(food => categories.add(food.category));
  return Array.from(categories).sort();
};

// Search and filter utilities
export const searchFoods = (query: string): FoodItem[] => {
  const lower = query.toLowerCase();
  return foodDatabase.filter(food =>
    food.name.toLowerCase().includes(lower) ||
    food.category.toLowerCase().includes(lower)
  );
};

export const getFoodsByCategory = (category: FoodCategory): FoodItem[] => {
  return foodDatabase.filter(food => food.category === category);
};

export const getFoodById = (id: string): FoodItem | undefined => {
  return foodDatabase.find(food => food.id === id);
};
